### ISSUE TITLE
Add —help functionality

### ISSUE THREAD

**Issue by robpearmain** [jounikor/pasmo#2]

**Comment by jounikor** [comment]
A compacted version of the pasmodoc.html descriptions would be great to add into the main program itself.

**Comment by jounikor** [comment]
See https://github.com/jounikor/pasmo/commit/56306ff1887d4cd91e271433cd3f0dac44c7a25f commit for the feature/help branch and the initial proposal for the content.

**Comment by jounikor** [comment]
Now merged to master.
